# Generated by Django 2.2.7 on 2019-11-27 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_options', models.CharField(choices=[('checking', 'CHECKING'), ('savings', 'SAVINGS')], default=('checking', 'CHECKING'), max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('bank_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bank_partner', to='bank.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=300)),
                ('bank_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_bank_partner', to='bank.Branch')),
                ('holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.Customer')),
            ],
        ),
    ]
